[package]
name = "ohw-wallets"
version = "0.0.1"
edition = "2021"
description = ""
license = ""


[features]
default = []
std = []
builtin = []

[build-dependencies]
cmake = { version = "0.1" }
bindgen = { version = "0.70" }
