[package]
name = "ohw-wallets"
version = "0.0.1"
edition = "2021"
description = ""
license = ""


[features]
default = []
std = []
builtin = []

[dependencies]
hex = { version = "0.4", default-features = false, features = ['alloc']}
anyhow = { version = "1.0", default-features = false }

[build-dependencies]
cmake = { version = "0.1" }
bindgen = { version = "0.70" }
