[package]
name = "oskey-wallet"
version = "0.0.1"
edition = "2021"
description = ""
license = ""

[features]
default = []
# Crypto backend selection (mutually exclusive):
# Note: enable both 'crypto-psa' and 'build' features to link against host lib.
crypto-psa = []
crypto-rs = [
  "dep:sha2",
  "dep:pbkdf2",
  "dep:hmac",
  "dep:ripemd",
  "dep:k256",
  "dep:p256",
  "dep:ed25519-dalek",
  "dep:x25519-dalek",
  "dep:chacha20poly1305",
]
build = ["dep:bindgen", "dep:cmake", "dep:pkg-config"]

[dependencies]
anyhow.workspace = true
bit-vec.workspace = true
heapless.workspace = true
zeroize.workspace = true

sha2 = { workspace = true, optional = true }
pbkdf2 = { workspace = true, optional = true }
hmac = { workspace = true, optional = true }
ripemd = { workspace = true, optional = true }
k256 = { workspace = true, optional = true }
p256 = { workspace = true, optional = true }
ed25519-dalek = { workspace = true, optional = true }
x25519-dalek = { workspace = true, optional = true }
chacha20poly1305 = { workspace = true, optional = true }

[dev-dependencies]
hex.workspace = true
bs58.workspace = true

[build-dependencies]
bindgen = { workspace = true, optional = true }
cmake = { workspace = true, optional = true }
pkg-config = { workspace = true, optional = true }
