syntax = "proto3";

package oskey;

message ReqData
{
	oneof payload
	{
		Unknown unknown = 2;
		VersionRequest version_request = 10;
		StatusRequest status_request = 20;
		UnlockRequest unlock_request = 25;
		LockRequest lock_request = 26;
		InitWalletCustomRequest init_custom_request = 30;
		InitWalletRequest init_request = 40;
		GenerateMnemonicRequest generate_mnemonic_request = 41;
		DerivePublicKeyRequest derive_public_key_request = 50;
		SignEthRequest sign_eth_request = 70;
		UserActionRequest user_action_request = 81;
		DeviceRequest device_request = 82;
		Fido2RegisterRequest fido2_register_request = 83;
		Fido2SignRequest fido2_sign_request = 84;
		ConfirmationControl confirmation_control = 85;
	}
}

message ResData
{
	oneof payload
	{
		ErrorResponse error_response = 1;
		Unknown unknown = 2;
		VersionResponse version_response = 11;
		StatusResponse status_response = 21;
		InitWalletResponse init_wallet_response = 31;
		DerivePublicKeyResponse derive_public_key_response = 51;
		SignResponse sign_response = 61;
		WaitForUserActionResponse wait_for_user_action_response = 80;
		DisplayResponse display_response = 90;
		ConfirmationPrompt confirmation_prompt = 91;
		Fido2Response fido2_response = 92;
		ConfirmationResult confirmation_result = 93;
	}
}

message Unknown
{
}

message VersionRequest
{
}

message VersionResponse
{
	string version = 1;
	Features features = 2;
	string sn = 3;
}

message Features
{
	bool initialized = 10;
	bytes support_mask = 20;
}

message StatusRequest
{
}

message StatusResponse
{
	bytes status_mask = 1;
}

message UnlockRequest
{
	bytes hash = 1;
	optional string pin_text = 2;
}

message LockRequest
{
}

message InitWalletCustomRequest
{
	string words = 2;
	string password = 3;
	bytes pin = 4;
	optional string pin_text = 5;
}

message InitWalletRequest
{
	uint32 length = 1;
	string password = 2;
	optional bytes seed = 3;
	bytes pin = 4;
	optional string pin_text = 5;
}

message GenerateMnemonicRequest
{
	uint32 length = 1;
	optional bytes entropy = 2;
}

message InitWalletResponse
{
	optional string mnemonic = 1;
}

message DerivePublicKeyRequest
{
	string path = 1;
}

message DerivePublicKeyResponse
{
	string path = 1;
	bytes public_key = 2;
}

message SignEthRequest
{
	int32 id = 1;
	string path = 2;
	oneof tx
	{
		AppEthTxEip2930 eip2930 = 10;
		AppEthTxEip191 eip191 = 20;
	}
	optional string debug_text = 5;
}

message AppEthTxEip191
{
	string message = 1;
	optional bool is_personal = 2;
}

message AppEthTxEip2930
{
	uint64 chain_id = 1;
	uint64 nonce = 2;
	optional string to = 5;
	string gas_price = 3;
	uint64 gas_limit = 4;
	string value = 6;
	optional bytes input = 7;
	optional bytes access_list = 8;
}

message SignResponse
{
	int32 id = 1;
	bytes message = 2;
	bytes public_key = 3;
	bytes pre_hash = 4;
	bytes signature = 5;
	optional uint32 recovery_id = 6;
}

enum AppError
{
	APP_ERROR_UNSPECIFIED = 0;
	APP_ERROR_FAILED = 1;
	APP_ERROR_BUSY = 2;
	APP_ERROR_REJECTED = 3;
	APP_ERROR_LOCKED = 4;
	APP_ERROR_NO_PENDING_ACTION = 5;
	APP_ERROR_DISPLAY_REQUIRED = 6;
	APP_ERROR_EXTERNAL_REQUEST_REQUIRED = 7;
	APP_ERROR_TRUSTED_ACTION_REQUIRED = 8;
	APP_ERROR_INVALID_ACTION = 9;
	APP_ERROR_UNLOCK_FAILED = 10;
}

message ErrorResponse
{
	AppError code = 1;
	string message = 2;
}

message WaitForUserActionResponse
{
}

enum UserAction
{
	USER_ACTION_UNSPECIFIED = 0;
	USER_ACTION_APPROVE = 1;
	USER_ACTION_REJECT = 2;
}

message UserActionRequest
{
	UserAction action = 1;
}

enum DisplayAction
{
	DISPLAY_ACTION_UNSPECIFIED = 0;
	DISPLAY_ACTION_READY = 1;
	DISPLAY_ACTION_MNEMONIC = 2;
	DISPLAY_ACTION_SIGN = 3;
	DISPLAY_ACTION_ERROR = 4;
	DISPLAY_ACTION_CONFIRM = 5;
}

message DisplayResponse
{
	DisplayAction action = 1;
	string text = 2;
	AppError error = 3;
	uint32 value = 4;
}

enum ConfirmationKind
{
	CONFIRMATION_KIND_UNSPECIFIED = 0;
	CONFIRMATION_KIND_SIGN = 1;
	CONFIRMATION_KIND_FIDO2 = 2;
}

message ConfirmationControl
{
	bool active = 1;
	string text = 2;
}

message ConfirmationPrompt
{
	bool active = 1;
	ConfirmationKind kind = 2;
	string text = 3;
}

message ConfirmationResult
{
	bool approved = 1;
}

enum DeviceAction
{
	DEVICE_ACTION_UNSPECIFIED = 0;
	DEVICE_ACTION_RESTART = 1;
	DEVICE_ACTION_RESET_STORAGE = 2;
}

message DeviceRequest
{
	DeviceAction action = 1;
}

message Fido2RegisterRequest
{
	string rp_id = 1;
	bytes user_id = 2;
}

message Fido2SignRequest
{
	bytes credential_id = 1;
	bytes rp_id_hash = 2;
	bytes hash = 3;
}

message Fido2Response
{
	bytes credential_id = 1;
	bytes data = 2;
}
