[package]
name = "oskey-chain"
version = "0.0.1"
edition = "2021"
description = ""
license = ""

[features]
default = ["crypto-rs"]
crypto-rs = ["oskey-wallet/crypto-rs"]
crypto-psa = ["oskey-wallet/crypto-psa"]
crypto-link = ["oskey-wallet/crypto-psa", "oskey-wallet/build"]

[dependencies]
oskey-wallet.workspace = true

alloy-consensus.workspace = true
anyhow.workspace = true
heapless.workspace = true

[dev-dependencies]
hex.workspace = true
