syntax = "proto3";

package oskey;

message ReqData
{
	oneof payload
	{
		Unknown unknown = 2;
		VersionRequest version_request = 10;
		StatusRequest status_request = 20;
		UnlockRequest unlock_request = 25;
		LockRequest lock_request = 26;
		InitWalletCustomRequest init_custom_request = 30;
		InitWalletRequest init_request = 40;
		DerivePublicKeyRequest derive_public_key_request = 50;
		SignEthRequest sign_eth_request = 70;
	}
	reserved 41, 81 to 85;
	reserved "generate_mnemonic_request", "user_action_request", "device_request",
		 "fido2_register_request", "fido2_sign_request", "confirmation_control";
}

message ResData
{
	oneof payload
	{
		ErrorResponse error_response = 1;
		Unknown unknown = 2;
		VersionResponse version_response = 11;
		StatusResponse status_response = 21;
		InitWalletResponse init_wallet_response = 31;
		DerivePublicKeyResponse derive_public_key_response = 51;
		SignResponse sign_response = 61;
		WaitForUserActionResponse wait_for_user_action_response = 80;
	}
	reserved 90 to 93;
	reserved "display_response", "confirmation_prompt", "fido2_response", "confirmation_result";
}

message Unknown
{
}

message VersionRequest
{
}

message VersionResponse
{
	string version = 1;
	Features features = 2;
	string sn = 3;
}

message Features
{
	bool initialized = 10;
	bytes support_mask = 20;
}

message StatusRequest
{
}

message StatusResponse
{
	bytes status_mask = 1;
}

message UnlockRequest
{
	bytes hash = 1;
	reserved 2;
	reserved "pin_text";
}

message LockRequest
{
}

message InitWalletCustomRequest
{
	string words = 2;
	string password = 3;
	bytes pin = 4;
	reserved 5;
	reserved "pin_text";
}

message InitWalletRequest
{
	uint32 length = 1;
	string password = 2;
	optional bytes seed = 3;
	bytes pin = 4;
	reserved 5;
	reserved "pin_text";
}

message InitWalletResponse
{
	optional string mnemonic = 1;
}

message DerivePublicKeyRequest
{
	string path = 1;
}

message DerivePublicKeyResponse
{
	string path = 1;
	bytes public_key = 2;
}

message SignEthRequest
{
	int32 id = 1;
	string path = 2;
	oneof tx
	{
		AppEthTxEip2930 eip2930 = 10;
		AppEthTxEip191 eip191 = 20;
	}
	optional string debug_text = 5;
}

message AppEthTxEip191
{
	string message = 1;
	optional bool is_personal = 2;
}

message AppEthTxEip2930
{
	uint64 chain_id = 1;
	uint64 nonce = 2;
	optional string to = 5;
	string gas_price = 3;
	uint64 gas_limit = 4;
	string value = 6;
	optional bytes input = 7;
	optional bytes access_list = 8;
}

message SignResponse
{
	int32 id = 1;
	bytes message = 2;
	bytes public_key = 3;
	bytes pre_hash = 4;
	bytes signature = 5;
	optional uint32 recovery_id = 6;
}

enum AppError
{
	APP_ERROR_UNSPECIFIED = 0;
	APP_ERROR_FAILED = 1;
	APP_ERROR_BUSY = 2;
	APP_ERROR_REJECTED = 3;
	APP_ERROR_LOCKED = 4;
	APP_ERROR_NO_PENDING_ACTION = 5;
	APP_ERROR_DISPLAY_REQUIRED = 6;
	APP_ERROR_EXTERNAL_REQUEST_REQUIRED = 7;
	APP_ERROR_TRUSTED_ACTION_REQUIRED = 8;
	APP_ERROR_INVALID_ACTION = 9;
	APP_ERROR_UNLOCK_FAILED = 10;
}

message ErrorResponse
{
	AppError code = 1;
	string message = 2;
}

message WaitForUserActionResponse
{
}
